apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: helloworld-operator
rules:
- apiGroups: [""]
  resources: [services]
  verbs: ['*']
- apiGroups: [""]
  resources: [namespaces]
  verbs: [get]
- apiGroups: [extensions]
  resources: [ingress]
  verbs: ['*']
- apiGroups: [apps]
  resources: [deployments]
  verbs: ['*']
- apiGroups: [monitoring.coreos.com]
  resources: [servicemonitors]
  verbs: [get, create]
- apiGroups: [apps]
  resourceNames: [helloworld-operator]
  resources: [deployments/finalizers]
  verbs: [update]
- apiGroups: [example.helmich.me]
  resources: ['*']
  verbs: ['*']
